export interface Piece {
    id: string;
    name: string;
    type: string;
    color: string;
    description: string;
    imageUrl: string;
    fake: boolean;
    level: number;
    special: boolean;
    comboVisual: boolean;
    power?: Power; 

  }

  export enum Power {
    BURBUJA_ANTIGRAVEDAD = "BURBUJA_ANTIGRAVEDAD",
    CHUPETE_SONICO = "CHUPETE_SONICO",
    ESCAPE_WRAP = "ESCAPE_WRAP",
  
    MECHA_JUMP_SHOT = "MECHA_JUMP_SHOT",
    CAMPO_MAGNETICO = "CAMPO_MAGNETICO",
    OVERBOOST_KAWAII = "OVERBOOST_KAWAII",
  
    PATADA_DE_PLASMA = "PATADA_DE_PLASMA",
    CONCENTRACION_ZEN = "CONCENTRACION_ZEN",
    COMBO_KICKS = "COMBO_KICKS",
  
    AMMO_RUSH = "AMMO_RUSH",
    POSTURA_IMPARABLE = "POSTURA_IMPARABLE",
    GOLPE_DE_AUTORIDAD = "GOLPE_DE_AUTORIDAD",
  
    DOUBLE_KATANA = "DOUBLE_KATANA",
    CORTE_TSUNAMI = "CORTE_TSUNAMI",
    SILENCIO_DEL_KOI = "SILENCIO_DEL_KOI",
  
    EXPLOSIVE_SHOT = "EXPLOSIVE_SHOT",
    SHOT_CANON = "SHOT_CANON",
    DINAMITE_EGG = "DINAMITE_EGG",
  
    PATADA_AEREA = "PATADA_AEREA",
    VUELO_TORNADO = "VUELO_TORNADO",
    LLAVE_IMPOSIBLE = "LLAVE_IMPOSIBLE",
  
    GARROTE_MAGICO = "GARROTE_MAGICO",
    GOLPE_DE_TIERRA = "GOLPE_DE_TIERRA",
    LLAMA_RITUAL = "LLAMA_RITUAL",
  
    DESTRUCTIVE_GUITAR = "DESTRUCTIVE_GUITAR",
    RIFF_SISMICO = "RIFF_SISMICO",
    FEEDBACK_INFERNAL = "FEEDBACK_INFERNAL",
  
    DISPARO_EXPLOSIVO = "DISPARO_EXPLOSIVO",
    TELETRANSPORTE_CORTO = "TELETRANSPORTE_CORTO",
    INTERFERENCIA_NEURAL = "INTERFERENCIA_NEURAL",
  
    EXPLOSION_DE_RABIA = "EXPLOSION_DE_RABIA",
    PELUCHAZO_LETAL = "PELUCHAZO_LETAL",
    SWING_BRUTAL = "SWING_BRUTAL",
  
    REVOLVER_SHOT = "REVOLVER_SHOT",
    ESCUDO_DE_PLOMO = "ESCUDO_DE_PLOMO",
    CARGA_DESBOCADA = "CARGA_DESBOCADA",
  
    SNAKEWOOD_SLASH = "SNAKEWOOD_SLASH",
    AIR_JUMP = "AIR_JUMP",
    SUPERMUSCULADO = "SUPERMUSCULADO",
  }
  
  